<!DOCTYPE html>
<html>
<head>
    <?=$this->jsonLd($this->job)?>
    <title><?=strip_tags($this->headTitle)?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta property="og:url" content="<?= $this->uriJob;?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?=strip_tags($this->headTitle); ?> - <?=$this->organizationName;?>" />
    <link rel="stylesheet" href="<?=$this->basePath("modules/Aviation/templates/de/job.css")?>" type="text/css">
    <style>
        form > div:hover {
            background-color: #eee;
            -webkit-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            -moz-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            cursor: pointer;
        }
        .company div {
            float: right;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="header"><img src="/modules/Aviation/templates/de/1-DC-Aviation-Header.png"></div>
    <div class="visual"><img src="/modules/Aviation/templates/de/plane.jpg"></div>
    <main>
        <p>
            <?php // TODO: Wo wird die Beschreibung gesetzt? Hier muss ein englisches Default rein. <?=$this->descriptionEditable ?>
            DC Aviation was created in 2007 from the former DaimlerChrysler Aviation, a subsidiary of DaimlerChrysler AG founded in 1998.
            With offices in Dubai, Malta and Moscow, the company's international presence is steadily increasing.
            Due to its long company history, the DC Aviation Group has extensive experience in the business aviation sector.
        </p>
        <div class="row">
            <div class="twelve columns title" itemprop="title">
                <?php echo $this->title; ?>
            </div>
        </div>
        <div class="row">
            <div class="six columns">
                <div class="panel">
                    <div class="panel-heading"><h4>Tasks</h4></div>
                    <div class="panel-body"><?=$this->requirements;?></div>
                </div>
            </div>
            <div class="six columns">
                <div class="panel">
                    <div class="panel-heading"><h4>Requirements</h4></div>
                    <div class="panel-body"><?=$this->qualifications;?></div>
                </div>
            </div>
            <?php if ($this->benefits): ?>
            <div class="twelve columns">
                <div class="panel">
                    <div class="panel-heading"><h4>Benefits</h4></div>
                    <div class="panel-body"><?=$this->benefits;?></div>
                </div>
            </div>
            <?php endif ?>
        </div>
        <div class="row">
            <div class="twelve columns">
            </div>
        </div>
        <p class="claim">Are you looking for a new professional challenge in a fast-growing company? Then get to know DC Aviation and get started with us. We look forward to receiving your application. </p>
    </main>
    <div class="footer-bar">
        <div class="footer-container">
            <div class="plane"><img src="/modules/Aviation/templates/de/logo_plane.png"></div>
            <div class="apply">
                <?=$this->jobApplyButtons(
                $this->applyData,
                [
                'sendImmediately' => true,
                'oneClickOnly' => false,
                'defaultLabel' => 'APPLY ONLINE NOW',
                'oneClickLabel' => null
                ]
                )?>
            </div>
            <br clear="all">
        </div>
    </div>
    <div class="company">
        <br>
        <address>
            <span><?= $this->organizationName?></span>
            <br />
            <span><?=$this->street?></span><br>
            <span><?=$this->postalCode?></span>
            <span><?=$this->city?></span>
            <br><br>
            <span><?=$this->phone?></span>
        </address>
        <div>
            <a href="https://www.linkedin.com/company/dc-aviation-gmbh/">
            <img src="<?=$this->basePath("modules/Aviation/templates/de/linkedin.png")?>">
            </a>
        </div>
        <br clear="all">
    </div>
</div>
</body>
</html>
