<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
       <?= $this->partial('mail/header', [
            'title' => $mail->getSubject(),
            'width'=>$width, 'mail_blue_color'=>$mail_blue_color,
            'mail_white_color' => $mail_white_color]); ?>
 <tr>
   <td align="center" valign="top">
                  <!-- CENTERING TABLE // -->
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
                    <tbody><tr>
                      <td align="center" valign="top">
                        <!-- FLEXIBLE CONTAINER // -->
                        <table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
                          <tbody><tr>
                            <td align="center" valign="top" width="500" class="flexibleContainerCell">
                              <table border="0" cellpadding="30" cellspacing="0" width="100%">
                                <tbody><tr>
                                  <td align="center" valign="top">

                                    <!-- CONTENT TABLE // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                      <tbody><tr>
                                        <td valign="top" class="textContent">
                                            <p><?=$this->content?></p>
                                        </td>
                                      </tr>
                                    </tbody></table>
                                    <!-- // CONTENT TABLE -->

                                  </td>
                                </tr>
                              </tbody></table>
                            </td>
                          </tr>
                        </tbody></table>
                        <!-- // FLEXIBLE CONTAINER -->
                      </td>
                    </tr>
                  </tbody></table>
                  <!-- // CENTERING TABLE -->
                </td>
              </tr>
            <!-- MODULE ROW // -->
         <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
