<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
<?= $this->partial('mail/header', [
    'title' => $mail->getSubject(),
    'width'=>$width, 'mail_blue_color'=>$mail_blue_color,
    'mail_white_color' => $mail_white_color]); ?>

<p style="<?=$style_p?>"><?=nl2br($this->content)?></p>

<?= $this->partial('mail/footer',
[
  'width' => $width,
  'mail_white_color' => $mail_white_color,
  'style' => $style_p
  ]); ?>
