<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2021 Cross Solution (http://cross-solution.de)
 * @author bleek@cross-solution.de
 * @license   MIT
 * phpcs:disable
 */

use Auth\Entity\User;

/*
 * Mail footer used in various mails via <?php echo $this->partial('mail/footer'); ?>
 */
?>
									<br>
									<p style="<?=$this->style?>">
                                        mit freundlichen Grüßen<br>
                                        <?php
                                            /** @var User $user */
                                            $hasUser =
                                                $this->auth()->isLoggedIn()
                                                && ($user = $this->auth()->getUser())
                                                && $user->getRole() != User::ROLE_USER
                                            ;
                                            if ($hasUser):?>
                                            <?=$user->getInfo()->getDisplayName(false) ?: 'HR-Team'?>

                                        <?php else: ?>
                                        HR-Team
                                        <?php endif ?>
									</p>
									<p style="<?=$this->style?>">
										DC Aviation GmbH<br>
										Stuttgart Airport<br>
										70629 Stuttgart, Germany<br>
										Phone <?=$hasUser && ($phone = $user->getInfo()->getPhone()) ? $phone : '+49 711 933 06-300' ?><br>
                                        Fax +49 711 933 06-473<br>
                                        <?php $mail = $hasUser && ($mail = $user->getInfo()->getEmail()) ? $mail : 'career@dc-aviation.com'; ?>
										Mail <?=$this->link($mail)?><br>
										<?=$this->link("https://www.dc-aviation.com")?><br>
									</p>
									<p style="<?=$this->style?>">
										Managing Directors: Michael K. Kuhn (CEO), Marc Ambrosius (CFO)<br>
										Registergericht Stuttgart HRB 19256
									</p>
									<br>
									<p style="<?=$this->style?>">
										This e-mail may contain confidential and/or privileged information. If you are
										not the intended recipient (or have received this e-mail in error) please notify
										the sender immediately and destroy this e-mail. Any unauthorized copying,
										disclosure or distribution of the material in this e-mail is strictly forbidden.
									</p>
								</td>
							</tr>
						</table>
					</td>
				</tr><!-- end:tr -->
			</tr>
		</table>
	</div>
</center>
</body>
</html>