<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\Info $user */
$user = $this->user->getInfo();
#$this->setSubject('Passwort vergessen');

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
<?= $this->partial('mail/header', [
    'title' => 'Passwort vergessen',
    'width'=>$width, 'mail_blue_color'=>$mail_blue_color,
    'mail_white_color' => $mail_white_color]); ?>

<h3 style="<?=$style_p?>">
  Sehr geehrter <?= $this->name; ?>
</h3>
<p style="<?=$style_p?>">
 Um ein neues Passwort zu setzen, klicken Sie bitte auf untenstehenden Link.
 Sollten Sie kein neues Passwort angefordert haben, brauchen Sie nichts weiter
 zu unternehmen.
</p>
<table border="0"
  cellpadding="0"
  cellspacing="0"
  width="50%"
  style="background-color: <?=$mail_blue_color?>;">
  <tr>
    <td align="center"
      valign="middle"
      style="padding-top:15px;padding-bottom:15px;padding-right:15px;padding-left:15px;"
    >
      <a style="color:#FFFFFF;text-decoration:none;font-family:Helvetica,Arial,sans-serif;font-size:20px;line-height:135%;"
        href="<?= $this->resetlink; ?>" target="_blank"
      >Neues Passwort</a>
    </td>
  </tr>
</table>
<?= $this->partial('mail/footer',
 [
   'width' => $width,
   'mail_white_color' => $mail_white_color,
   'style' => $style_p
   ]); ?>
