<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2021 Cross Solution <http://cross-solution.de>
 */

/*
 * Available Variables:
 *
 * string $inviter          Name of inviter or his/her email address
 * string $organization     Name of the organization to which the invitation is made
 * string $token            Confirmation token
 * string $user             User who gets invited
 * boolean $hasAssociation  Wether or not the user is already assigned to an organization.
 *
 * If $hasAssociation is TRUE, the following variables are available:
 *
 * boolean $isOwner         Wether or not the user is the owner of his/her associated organization
 * string  $currentOrganization The name of the current organization.
 *
 */

include(__DIR__ . '/' . 'vars.inc.phtml');
#$this->setSubject('Einladung in das Team von ' . $this->organization);

?>
<?= $this->partial('mail/header', [
    'title' => 'Einladung ins Firmen-Team',
    'width' => $width,
    'mail_blue_color' => $mail_blue_color,
    'mail_white_color' => $mail_white_color
]);
?>

<h3 style="color:<?=$mail_blue_color?>;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:bold;margin-top:0;margin-bottom:3px;text-align:left;">
    <?= ($this->user) ? sprintf($this->translate('Hello %s'), $this->user) : $this->translate('Hello') ?>
    ,
</h3>
<div mc:edit="body"
        style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%;">
    <?= sprintf($this->translate('%s invited you to join the team of %s'), $this->inviter, $this->organization) ?>
</div>

<table border="0" cellpadding="0" cellspacing="0" width="50%" class="emailButton" style="background-color: <?=$mail_blue_color?>;">
    <tr>
        <td align="center" valign="middle" class="buttonContent" style="padding: 15px;">
            <a style="color:#FFFFFF;text-decoration:none;font-family:Helvetica,Arial,sans-serif;font-size:20px;line-height:135%;"
                href="<?= $this->serverUrl($this->url) ?>" target="_blank">Einladung akzeptieren</a>
        </td>

        <?php
        if ($this->hasAssociation) {
            if ($this->isOwner) {
                echo sprintf(
                    $this->translate('<strong>Please note: </strong> You are currently the owner of <b>%s</b>. Accepting this invitation will delete your organization.'),
                    $this->currentOrganization
                );
            } else {
                echo sprintf(
                    $this->translate('<strong>Please note: </strong> You are currently assigned as an employee to <b>%s</b>. Accepting this invitation will remove this association.'),
                    $this->currentOrganization
                );
            }
        }
        ?>
    </tr>
    </table>

<?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>

