<?php
/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2018 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */

$width            = "600px";
$mail_blue_color  = "#7b1738"; // color ist used in srv/Mail/NewApplication.php hardcoded
$mail_white_color = "#fff";
$style_p          = "font-family: Arial, Helvetica, sans-serif; font-weight: 400; font-size: 15px; line-height: 1.8;";