<?php
/**
 * YAWIK
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('Aviation'))->setSeparator(' - ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName("keywords", "Open Surce Bewerbermanagement System, Bewerberverwaltung");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);

$this->configHeadScript()->prependFile($this->basepath('dist/js/core.js'));

$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath('modules/Aviation/dist/Aviation.css'));


foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
<link rel="icon" href="<?=$this->basePath('modules/Aviation/img/cropped-yawik-small-32x32.jpg')?>" sizes="32x32" />
    <link rel="icon" href="<?=$this->basePath('modules/Aviation/img/cropped-yawik-small-192x192.jpg')?>" sizes="192x192" />
    <link rel="apple-touch-icon-precomposed" href="<?=$this->basePath('modules/Aviation/img/cropped-yawik-small-180x180.jpg')?>" />
    <meta name="msapplication-TileImage" content="<?=$this->basePath('modules/Aviation/img/cropped-yawik-small-270x270.jpg')?>" />
</head>
<body>
<main id="content" class="col-md-12">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<?=$this->partial('aviation/footer')?>
<?php echo $this->partial("piwik") ?>
</body>
</html>
